import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Header } from "@/components/Header";
import { Divider } from "@chakra-ui/layout";
import { Footer } from "@/components/Footer";

interface MainLayoutProps {
  children: JSX.Element[] | JSX.Element;
}

export default function MainLayoutProps({ children }: MainLayoutProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>{children}</main>
      <Divider />
      <Footer />
    </div>
  );
}
